AgileBoxScore/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AgileBoxScore.Models
{
    public class Game
    {
        public Game() { }
        public Game(String id, Int32 inning, Boolean isTop, String home, String away,
            Int32 homeScore, Int32 awayScore, Int32 homeHits, Int32 awayHits,
            Int32 homeError, Int32 awayError, Int32 outs)
        {
            Id = id;
            Inning = inning;
            IsTopOfInning = isTop;
            HomeTeam = home;
            AwayTeam = away;
            HomeRuns = homeScore;
            AwayRuns = awayScore;
            HomeHits = HomeHits;
            AwayHits = awayHits;
            HomeError = homeError;
            AwayError = awayError;
            Outs = outs;
        }

        public String Id { get; set; }
        public Int32 Inning { get; set; }
        public Boolean IsTopOfInning { get; set; }
        public String HomeTeam { get; set; }
        public String AwayTeam { get; set; }
        public Int32 HomeRuns { get; set; }
        public Int32 AwayRuns { get; set; }
        public Int32 HomeHits { get; set; }
        public Int32 AwayHits { get; set; }
        public Int32 HomeError { get; set; }
        public Int32 AwayError { get; set; }
        public Int32 Outs { get; set; }
    }
}

AgileBoxScore/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgileBoxScore.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }
    }
}

AgileBoxScore/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AgileBoxScore.Hubs;
using AgileBoxScore.Models;

namespace AgileBoxScore.Controllers
{
    public class GameController : ApiController
    {

        private GameHub _hub;

        public GameController() { _hub = new GameHub(); }

        public HttpResponseMessage Get()
        {
            return Request.CreateResponse(HttpStatusCode.OK);
        }


        public IHttpActionResult Put(String id, Game game)
        {
            _hub.UpdateGame(id, game);

            return Ok();
        }
    }
}

AgileBoxScore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgileBoxScore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AgileBoxScore/Views/Chat/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>ChatR</h2>


<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>

@section Scripts {
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.2.0.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src="~/Scripts/ChatR.js"></script>
}

AgileBoxScore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AgileBoxScore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AgileBoxScore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>MongoBaseball.NET</h1>
    <p class="lead">Baseball Scores from Around the League</p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Pittsburgh - St. Louis</h2>
        <p>
            <table class="table" id="pitstl">
                <thead>
                    <tr>
                        <th>Team</th>
                        <th>R</th>
                        <th>H</th>
                        <th>E</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </p>
        <p></p>
    </div>
    <div class="col-md-4">
        <h2>Washington - Philadelphia</h2>
        <p>
            <table class="table" id="wshphl">
                <thead>
                    <tr>
                        <th>Team</th>
                        <th>R</th>
                        <th>H</th>
                        <th>E</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </p>
        <p></p>
    </div>
    <div class="col-md-4">
        <h2>Texas - Baltimore</h2>
        <p>
            <table class="table" id="texbal">
                <thead>
                    <tr>
                        <th>Team</th>
                        <th>R</th>
                        <th>H</th>
                        <th>E</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </p>
        <p></p>
    </div>
</div>

@section Scripts {
<!--Reference the SignalR library. -->
<script src="/Scripts/jquery.signalR-2.2.0.js"></script>
<!--Reference the autogenerated SignalR hub script. -->
<script src="/signalr/hubs"></script>
<script src="~/Scripts/BoxScore.js"></script>
}

AgileBoxScore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MongoBaseball.NET", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("ChatR", "Index", "Chat")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>